### ISSUE TITLE
Request: Make a version for .Net 6.0

### ISSUE THREAD

**Issue by Jenrikku** [NedoProgrammer/TinyDialogsNet#2]
I'm developing a project that depends on Tiny File Dialogs to work with file input but it's all based on .Net 6.0 and the NuGet package refuses to install. Would it be possible to make a version compatible with .Net 6.0?

**Comment by nedoxff** [comment]
Hello! Yes, it's totally possible. In fact, you can change the version yourself in the .csproj file and it (should) compile just fine.
I can upload a new minor version to nuget which supports net6.0, if that's comfortable for you!

**Comment by Jenrikku** [comment]
I've just checked some features added in .Net 7.0 and I think I have changed my mind. Still, having a NuGet Package that allows for .Net 6.0 should make it more accessible to people. Good job with this project by the way!

**Comment by nedoxff** [comment]
Thanks! If you don't mind, I'll close the issue, but I'll add the net6.0 version anyway.

**Comment by nedoxff** [comment]
There is now a 1.1.1 version that supports both net6.0 and net7.0!
